# Repository settings intended for the GitHub Settings app:
# https://github.com/apps/settings
repository:
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks: null
      enforce_admins: true
      required_linear_history: true
      restrictions: null
